Doc/add documentation
Splendor-Mobile-Game/ServerSide pull request #103
Opened 2023-04-13 18:59 UTC by Vertonowsky

Added documentation for #81 and #82 issues.

2023-04-13 21:18 UTC, kestivvi requested changes
Very good documentation. You have even said what is being validated. Please, resolve merge conflicts and we can merge it.

2023-04-13 21:18 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
> + * Reaction sent when new player joins to already created room.
Maybe I'm nitpicking, but it should be "...when the player **wants** to join an already...".

2023-04-14 06:10 UTC, Vertonowsky commented
> Very good documentation. You have even said what is being validated. Please, resolve merge conflicts and we can merge it.

Thanks, I will do it later

2023-04-14 16:17 UTC, kestivvi approved these changes

2023-04-14 16:22 UTC, sssadpeach15 approved these changes
nice.

2023-04-14 16:42 UTC, merged