added kick reaction
Splendor-Mobile-Game/ServerSide pull request #107
Opened 2023-04-15 09:45 UTC by VEXI19

I don't know if that was needed but I also created a niew exception when a user has no permission for an action (PerrmissionDeniedExeption)

2023-04-15 16:27 UTC, kestivvi requested changes
Good job man. Just add some java docs.

2023-04-15 16:27 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/exceptions/PerrmissionDeniedExeption.java
> +public class PerrmissionDeniedExeption extends Exception {
Add one line java doc.

2023-04-15 16:27 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/Kick.java
>  public class Kick extends Reaction {
Add comprehensive java doc for this class. See how `StartGame` reaction does this or `GetTokens` (that will be merged) for example.

2023-04-15 17:21 UTC, Vertonowsky submitted a review, later dismissed

2023-04-16 20:50 UTC, kestivvi approved these changes
Great

2023-04-16 21:18 UTC, sssadpeach15 approved these changes

2023-04-16 21:54 UTC, merged