added buyReservedMine reaction
Splendor-Mobile-Game/ServerSide pull request #109
Opened 2023-04-16 17:53 UTC by VEXI19

Also created isCardReserved in a User class

2023-04-16 21:22 UTC, kestivvi requested changes

2023-04-16 21:22 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/App.java
Please, do not format already pretty code, that has been written by someone else if this pull request doens't serve this purpose. Please, revert it.

2023-04-16 21:23 UTC, kestivvi commented
Nicely written class ✨✨

I haven't test that yet. Also please, turn of your code formatter. It's destroying some pieces of code xDDDDDDD

2023-04-18 16:48 UTC, Vertonowsky approved these changes, later dismissed

2023-04-18 20:51 UTC, kestivvi commented
Now you have to resolve merge conflicts as well 🗿

2023-04-20 09:30 UTC, kestivvi requested changes
I hadn't been meticulous then and now I've found things to be improved. Sry about that 😥

2023-04-20 09:30 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/BuyReservedMine.java
> +            buyer.buyCard(boughtCard);
You forgot about removing this card from reserved cards.

2023-04-20 09:30 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/BuyReservedMine.java
> +            throw new UserTurnException("It is not a user's turn");
If it is user's turn, you should also check if this user has did some action. Use `hasPerformedAction` field that is in `User`.

2023-04-21 17:14 UTC, kestivvi requested changes

2023-04-21 17:14 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/game/model/User.java
> +    public void removeCardFromResrved(Card card) {
Is this a typo?

2023-04-21 17:16 UTC, VEXI19 commented on src/main/java/com/github/splendor_mobile_game/game/model/User.java
> +    public void removeCardFromResrved(Card card) {
in did, it is

2023-04-21 17:17 UTC, VEXI19 commented on src/main/java/com/github/splendor_mobile_game/game/model/User.java
> +    public void removeCardFromResrved(Card card) {
well spotted

2023-04-21 17:18 UTC, kestivvi approved these changes, later dismissed
Great work!!! 🎉🎊🎊👌

2023-04-21 17:45 UTC, kestivvi approved these changes
👌🎊🎉🎈

2023-04-22 12:37 UTC, Vertonowsky approved these changes

2023-04-22 19:43 UTC, merged