Added MakeReservationFromDeck reaction
Splendor-Mobile-Game/ServerSide pull request #111
Opened 2023-04-16 20:07 UTC by v4m3rrr

Solved issue #64

2023-04-16 21:10 UTC, kestivvi requested changes
Fascinating 😮😮 You've solved like 3 high priority not so easy issues!! That's a lot of code!

I put some comments down the road.

2023-04-16 21:10 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromDeck.java
> +                        card.getCost(TokenType.ONYX)
I like this way of building a response.

2023-04-16 21:10 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromDeck.java
> +            throw new TokenCountException("There is not enough golden joker on table");
User can reserve a card when there is no more gold tokens. In such situation they reserve a card, but don't get the gold token.

2023-04-16 21:10 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromDeck.java
> +            throw new TokenCountException("Reached max token count on hand");
I don't remeber exact rules, but I think user can reserve a card in such situation, they simply just don't get the gold token. 

Do you remember what should be done in such case? @Vertonowsky @KamilDevelopments @EaZZyHK @sssadpeach15

2023-04-16 21:10 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromDeck.java
> +
I don't let those blank lines of code to be approved. If you want to get more lines of code, to be higher in the ranking you should add java docs to every class, method and field you've added. Free lines man.

2023-04-17 21:23 UTC, kestivvi submitted a review, later dismissed
Magnificent 💎🏆🪄🍕

Just resolve merge conflicts and it goes in!

2023-04-18 16:09 UTC, kestivvi requested changes

2023-04-18 16:09 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromDeck.java
>   *              "id": "0ba9cba8-3bc0-42fe-b24f-25d7b52fcd2c",
There should be `uuid`

2023-04-18 16:17 UTC, kestivvi approved these changes
🤩🤩🍕

2023-04-18 16:48 UTC, Vertonowsky approved these changes

2023-04-18 17:45 UTC, merged