Created EnvConfigTests
Splendor-Mobile-Game/ServerSide pull request #115
Opened 2023-04-17 21:59 UTC by patrykcalka

Created 5 unit tests for EnvConfig class. These tests cover base functionality of EnvConfig class. Issue #51

2023-04-18 10:02 UTC, sssadpeach15 submitted a review, later dismissed

2023-04-18 12:52 UTC, kestivvi requested changes
Great simple tests! 🎉🎉 

I would add also test checking what if some value is empty ie.
```env
PORT=
CONNECTION_LOST_TIMEOUT_SEC=100
PING_INTERVAL_MS=1000
CONNECTION_CHECK_INTERVAL_MS=1000
LOGS_DIR=./logs/
```

and what if in the config file there are some additional fields ie.
```env
PORT=8887
a=312
CONNECTION_LOST_TIMEOUT_SEC=100
bc=dsa
PING_INTERVAL_MS=1000
CONNECTION_CHECK_INTERVAL_MS=1000
LOGS_DIR=./logs/
```

I plan in the distant future to refactor EnvConfig class, so it does not receive path to the file but simply just `FileHandler` or something so creating files wouldn't be necessary.

2023-04-18 12:52 UTC, kestivvi commented on src/test/java/com/github/splendor_mobile_game/websocket/config/EnvConfigTests.java
> +            EnvConfig config = new EnvConfig();
Unfortunately you should not check for the default config which is in the root directory, simply because it will change a lot.

2023-04-26 21:18 UTC, kestivvi approved these changes
What a awesome test!! Great work! 🎊🎉✨

2023-04-29 12:36 UTC, merged