corrected typo
Splendor-Mobile-Game/ServerSide pull request #129
Opened 2023-04-21 17:39 UTC by VEXI19

KICK_ANNOUNCEMENT server message typo corrected

2023-04-21 17:43 UTC, kestivvi commented
There is also a typo

https://github.com/Splendor-Mobile-Game/ServerSide/blob/b0c444a9f84b735c44b898edaf648126d30db5de/src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/Kick.java#L26

2023-04-21 18:06 UTC, kestivvi requested changes
There's still a typo in the 26th line

2023-04-21 18:14 UTC, kestivvi approved these changes

2023-04-22 11:00 UTC, sssadpeach15 approved these changes

2023-04-22 19:43 UTC, merged