Make reservation from table reaction
Splendor-Mobile-Game/ServerSide pull request #130
Opened 2023-04-22 15:04 UTC by Antonidass5

finished make reservation from table reaction 🤙

2023-04-22 19:13 UTC, kestivvi requested changes

2023-04-22 19:13 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromTable.java
> +        public CardDataResponse card;
Change the name of this card field, it's not clear what it is. Also please update documentation of this class that is before class declaration.

2023-04-22 19:13 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromTable.java
> +        public boolean goldenToken;
Maybe `gotGoldenToken` would be more meaningful name

2023-04-22 19:13 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/MakeReservationFromTable.java
> +            throw new UserReservationException("User reached the limit of reserved cards per game");
This isn't proper check. Rules of the game say something else. This is a bug and this method was introduced earlier by someone else. I will write a new issue about fixing it. So currently leave it as it is.

Rules say, there can be only 5 cards reserved in a single moment. Not that one player can reserve only 5 cards throughout the entire game.

2023-04-23 12:41 UTC, kestivvi approved these changes, later dismissed
Superb 💎

2023-04-23 15:13 UTC, Vertonowsky approved these changes, later dismissed

2023-04-23 20:18 UTC, kestivvi approved these changes

2023-04-23 20:39 UTC, walczak1404 approved these changes

2023-04-23 20:45 UTC, merged