Create LICENSE
Splendor-Mobile-Game/ServerSide pull request #40
Opened 2023-03-25 17:36 UTC by EaZZyHK

The name of the license might need to be changed

2023-03-25 17:48 UTC, EaZZyHK commented
After successful approval, I want to add the same file to our second repository [ClientSide ](https://github.com/Splendor-Mobile-Game/ClientSide) directly to the `develop` branch.

2023-03-25 18:01 UTC, kestivvi commented
I propose waiting till thursday and ask our lecturer if this license is properly composed.

2023-03-26 08:27 UTC, Vertonowsky approved these changes, later dismissed

2023-03-31 09:11 UTC, sssadpeach15 approved these changes, later dismissed

2023-03-31 11:31 UTC, kestivvi requested changes

2023-03-31 11:31 UTC, kestivvi commented on LICENSE
> +Entire repository is owned by SGGW (Warsaw University of Life Sciences) and is associated with the subject "Software engineering"
we must point out that it is created as part of the course `name` by students of SGGW 2021/2024 or something like that.

2023-03-31 12:15 UTC, kestivvi approved these changes

2023-03-31 12:20 UTC, merged