Add java docs, also rename some classes and functions
Splendor-Mobile-Game/ServerSide pull request #45
Opened 2023-03-28 22:26 UTC by kestivvi

I have added a milion java docs to classes and functions I'd created. Maybe I will wait with merging it until the #44 is merged, because it was renaming some classes as well and then I improve this PR.

2023-03-28 22:30 UTC, kestivvi commented
I should've also add TODOs to functions that are possible to be unit tested.

- [ ] Added TODOs

2023-03-29 19:45 UTC, Vertonowsky requested changes

2023-03-29 19:45 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +     */
I think that commenting this part of the code is useless.

2023-03-29 19:45 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
? xd This type of comments makes code harder to read, not easier

2023-03-29 20:07 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
So what are you proposing? To remove all java docs from the all exceptions?

2023-03-29 20:43 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
yeah. Also we don't need comments on basic functions with just 1/2 lines of code. It's just making a bush from our code

2023-03-29 20:44 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +     */
Same here. Function is so simple, that there shouldn't be any comments.

2023-03-29 21:04 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
I wonder if our lecturer wouldn't require everything to be documented. Even the simplest functions.

2023-03-29 21:06 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
However, if you would like, I can remove java docs from exceptions and the simplest functions. What's the decision, Mr. Programmer?

2023-03-29 21:28 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
We can wait untill tomorrow and we will ask about the documentation. But in my opinion not always good = a lot.

2023-03-29 21:29 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
I agree with you

2023-03-30 20:52 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
Lecturer has said that we can remove java docs from constructors in exceptions if they are default implementations, leaving only general java doc about exception class as a whole. He said also we can remove java docs from getter and setters and other functions that contain only one line or two and the method name says everything you want to know.

2023-03-30 20:54 UTC, kestivvi commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
> +    /** Constructs a new JsonIsNullException with no message. */
I've just implemented those changes in my java docs.

2023-04-02 09:31 UTC, Vertonowsky requested changes

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketConnectionChecker.java
> +    /** The WebSocket connection this instance is monitoring. */
It says nothing to me. Refactor or remove. (i prefer removing)

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/Message.java
> +    /** The websocket hashcode of the receiver of the message. */
"Each connection between User and Server is identified by some ID. `receiverHashcode` is the ID of the connection.

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/Message.java
> +    /** The content of the message. */
unnecessary

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/Message.java
> +     */
unnecessary

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionChecker.java
> +     */
unnecessary

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionChecker.java
> +    /** Called when the WebSocket connection is closed. */
unnecessary

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionChecker.java
> +     */
unnecessary

2023-04-02 09:31 UTC, Vertonowsky commented on src/main/java/com/github/splendor_mobile_game/websocket/utils/CustomException.java
> +     */
unnecessary

2023-04-02 15:37 UTC, kestivvi commented
I've followed your lead @Vertonowsky.

2023-04-02 15:46 UTC, Vertonowsky approved these changes

2023-04-02 15:49 UTC, merged